"""
Auto-mined factors — generated by Alpha Miner autonomous pipeline
Session 5 (2026-06-02): 9 factors. Registered at import time via register_auto_mined.register_all().
"""
from . import register_auto_mined

register_auto_mined.register_all()
